import {buildFirstMessage, buildSystemPrompt} from '../systemPrompt';
import {
  AWAY_STEP_ID,
  formatRecap,
  LAST_STEP_ID,
  STEPS,
  stepIndexById,
} from '../script';

describe('script.ts step table', () => {
  it('keeps the away step (歯磨き＋コンタクト) as the only away-location step', () => {
    const awayIndices = STEPS.filter(s => s.location === 'away').map(s => s.id);
    expect(awayIndices).toEqual([AWAY_STEP_ID]);
  });

  it('orders charge-phone before lights-off, and lights-off before put-down-phone', () => {
    // 05章「見つかった順番の問題」②: 暗闇でケーブルを探させない。
    const chargeIndex = stepIndexById('charge_phone');
    const lightsIndex = stepIndexById('turn_off_lights');
    const putDownIndex = stepIndexById('put_down_phone');
    expect(chargeIndex).toBeLessThan(lightsIndex);
    expect(lightsIndex).toBeLessThan(putDownIndex);
  });

  it('ends with the close-eyes step', () => {
    expect(STEPS[STEPS.length - 1].id).toBe(LAST_STEP_ID);
  });

  it('formats the previous-night recap per mode', () => {
    expect(formatRecap('normal', 7)).toContain('7');
    expect(formatRecap('normal', 7)).not.toBe(formatRecap('strict', 7));
  });
});

describe('buildSystemPrompt', () => {
  it('includes every step label and the chosen mode line for a fresh call', () => {
    const prompt = buildSystemPrompt('normal');
    for (const step of STEPS) {
      expect(prompt).toContain(step.label);
      expect(prompt).toContain(step.line.normal);
    }
    expect(prompt).not.toContain(STEPS[0].line.strict);
  });

  it('instructs a silent hangup after the away step without explaining the interruption', () => {
    const prompt = buildSystemPrompt('normal');
    expect(prompt).toContain('endCall');
    expect(prompt).toContain('中断については説明しない');
  });

  it('adds a resume note for redial that names the step to continue from', () => {
    const prompt = buildSystemPrompt('normal', {
      lastCompletedStepIndex: 1, // completed steps 0-1 (opening, tv)
      isRedial: true,
      isAwayReconnect: false,
    });
    const resumeStep = STEPS[2];
    expect(prompt).toContain(resumeStep.label);
    expect(prompt).toContain('続きからいこう');
  });

  it('adds an "おかえり" resume note for an away reconnect instead of a redial note', () => {
    const awayIndex = stepIndexById(AWAY_STEP_ID);
    const prompt = buildSystemPrompt('strict', {
      lastCompletedStepIndex: awayIndex,
      isRedial: false,
      isAwayReconnect: true,
    });
    expect(prompt).toContain('おかえり');
    expect(prompt).not.toContain('続きからいこう');
  });

  it('only injects the previous-night recap note on a fresh (non-resume) call', () => {
    const fresh = buildSystemPrompt('normal', undefined, 7);
    expect(fresh).toContain('7');

    const resumed = buildSystemPrompt('normal', {
      lastCompletedStepIndex: 1,
      isRedial: true,
      isAwayReconnect: false,
    }, 7);
    // recap talk would be confusing wedged into a mid-flow resume
    expect(resumed).not.toContain('前夜');
  });
});

describe('buildFirstMessage', () => {
  // firstMessage is always left undefined (for every case, not just resume)
  // so the opening line is generated by the LLM from the system prompt too --
  // a literal firstMessage plays before any LLM turn happens, which means
  // report_step never fires for the opening step and the app can't track it.
  it('leaves firstMessage undefined for a fresh call', () => {
    expect(buildFirstMessage('normal')).toBeUndefined();
  });

  it('leaves firstMessage undefined for redial/away-reconnect too', () => {
    expect(
      buildFirstMessage('normal', {
        lastCompletedStepIndex: 0,
        isRedial: true,
        isAwayReconnect: false,
      }),
    ).toBeUndefined();
    expect(
      buildFirstMessage('normal', {
        lastCompletedStepIndex: 0,
        isRedial: false,
        isAwayReconnect: true,
      }),
    ).toBeUndefined();
  });
});
